### ISSUE TITLE
FW crash when loading FreeDOS 1.3 with UltraDMA 0 enabled

### ISSUE THREAD

**Issue by aperezbios** [ZuluIDE/ZuluIDE-firmware#104]
With firmware v2024.08.15 (latest as of today), booting FreeDOS works fine until the UDMA FreeDOS driver loads, at which point the ZuluIDE firmware crashes. Disabling UDMA mode in zuluscsi.ini results in the boot working fine, so this appears to be a UDMA-specific bug.

[zululog.txt](https://github.com/user-attachments/files/16642001/zululog.txt)
[zuluerr.txt](https://github.com/user-attachments/files/16642002/zuluerr.txt)

**Comment by morio** [comment]
Should be fixed in this pull request: https://github.com/ZuluIDE/ZuluIDE-firmware/pull/107
