### ISSUE TITLE
Add support for multi-file cuesheets

### ISSUE THREAD

**Issue by nvllsvm** [ZuluIDE/ZuluIDE-firmware#115]
It's valid for a cuesheet to reference multiple files (ex. separate files for each track). The disc preservation community [redump.org](redump.org) encourages this style when archiving physical media. All of my personal disc dumps are made in this style. However, I cannot use these dumps as-is with ZuluIDE.

ZuluIDE currently ignores .cue files when scanning for images. It will only read from a .cue file after initially finding a .bin file with the same stem. Even then, the files referenced in the .cue file are not utilitized - only the initial .bin is. This can and has resulted in ZuluIDE exposing an incomplete CD to the host.

It is possible to work around this by merging the separate files into a single bin (ex. `binmerge <split.cue> <merged_name>`), though I'm hoping that ZuluIDE could simply handle the split cuesheets instead. 

### Example:
The CD http://redump.org/disc/96103/ has two data tracks that are referenced by the host as a single drive. I'm lacking in the specifics of why, but iirc track 1's file list references sectors on track 2. With ZuluIDE, this results in the host being able to see the list of files, but encountering an error when attempting to read from them.

**Comment by aperezbios** [comment]
@nvllsvm acknowledged, and completely agreed on all points. This is estimated to be 10-20 hours worth of work, which is the only reason it isn't done yet.

**Comment by PetteriAimonen** [comment]
There is now a test build available here: https://github.com/ZuluIDE/ZuluIDE-firmware/actions/runs/11616020341

The files have to be placed in a subfolder, for example:

     /Rise_of_the_Triad/Rise of the Triad - The HUNT Begins (USA).cue
     /Rise_of_the_Triad/Rise of the Triad - The HUNT Begins (USA) (Track 1).bin
     /Rise_of_the_Triad/Rise of the Triad - The HUNT Begins (USA) (Track 2).bin

**Comment by nvllsvm** [comment]
Confirmed, thank you!

**Comment by aperezbios** [comment]
Support for multi-file cuesheets is now implemented in the most recent [v2024.11.13](https://github.com/ZuluIDE/ZuluIDE-firmware/releases/tag/v2024.11.13) firmware release
