### ISSUE TITLE
CUE file support for OGG/MP3 playback

### ISSUE THREAD

**Issue by InterClaw** [ZuluIDE/ZuluIDE-firmware#130]
I'm not sure if this is already supported or not. I don't have a way of really testing it. But does the ZuluIDE support CUE files that play OGG or MP3 files as CD audio playback, instead of additional BIN files?

**Comment by aperezbios** [comment]
@InterClaw ZuluIDE does not support this, and given the lack of any sort of floating point math capabilities of the two ARM Cortex M0+ cores, there are multiple technical reasons why the RP2040 microcontroller is not suitable for performing mp3/ogg decoding, when its primary role in the context of ZuluIDE is to send and receive data in a timely manner. 

Fortunately, we exist in an era where 64GB+ SD/microSD cards are cheap and plentiful. It's entirely possible that a future hardware variant of ZuluIDE could allow for such improvements, but no such plan for such hardware exists or is in motion at this time.
