### ISSUE TITLE
Implement support for emulating specific CD/DVD-ROM models

### ISSUE THREAD

**Issue by aperezbios** [ZuluIDE/ZuluIDE-firmware#30]
I'd like to add a generic mechanism to add a list of specific D-ROM drives to be supported, such that you can specify which drive you want to report as.

Here's an example of the output from a Matsushita CR-585 24X CD-ROM drive:

```standard INQUIRY:
  PQual=0  Device_type=5  RMB=1  LU_CONG=0  version=0x05  [SPC-3]
  [AERC=0]  [TrmTsk=0]  NormACA=1  HiSUP=1  Resp_data_format=2
  SCCS=0  ACC=0  TPGS=0  3PC=0  Protect=0  [BQue=0]
  EncServ=0  MultiP=0  [MChngr=0]  [ACKREQQ=0]  Addr16=0
  [RelAdr=0]  WBus16=0  Sync=0  [Linked=0]  [TranDis=0]  CmdQue=0
  [SPI: Clocking=0x0  QAS=0  IUS=0]
    length=96 (0x60)   Peripheral device type: cd/dvd
 Vendor identification: MATSHITA
 Product identification: CD-ROM CR-585   
 Product revision level: ZS15
 00     05 80 05 32 5b 00 00 00  4d 41 54 53 48 49 54 41    ...2[...MATSHITA
 10     43 44 2d 52 4f 4d 20 43  52 2d 35 38 35 20 20 20    CD-ROM CR-585   
 20     5a 53 31 35 20 20 20 20  20 20 20 20 20 20 20 20    ZS15            
 30     39 37 30 34 30 37 31 37  00 00 00 00 00 00 00 00    97040717........
 40     00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00    ................
 50     00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00    ................
  MATSHITA  CD-ROM CR-585     ZS15
  Peripheral device type: cd/dvd
  MATSHITA  CD-ROM CR-585     ZS15
  Peripheral device type: cd/dvd
  MATSHITA  CD-ROM CR-585     ZS15
  Peripheral device type: cd/dvd
  MATSHITA  CD-ROM CR-585     ZS15
  Peripheral device type: cd/dvd
Read Capacity results:
   Last LBA=33939 (0x8493), Number of logical blocks=33940
   Logical block length=2048 bytes
Hence:
   Device size: 69509120 bytes, 66.3 MiB, 0.07 GB
  MATSHITA  CD-ROM CR-585     ZS15
  Peripheral device type: cd/dvd
Supported VPD pages VPD page:
```

**Comment by nvllsvm** [comment]
@aperezbios How did you generate that output? I'd like to do the same for one my drives.

**Comment by jbehrends** [comment]
+1

I think this would be a worth while feature to implement sooner than later along with some documentation/examples on some popular makes/models you can set it to.  

I just spent quite a while attempting to get OS/2 3.0 to recognize and install from a ISO presented from my ZuluIDE.  I got it working in the end, but I'd be curious if this feature would have allowed me to set the device make/model/ID/etc to mimic a cdrom drive that was super common around the mid 90's time frame and ultimately be recognized out of the box by whatever legacy OS/Software your using.

**Comment by aperezbios** [comment]
@jbehrends FYI support for setting ATAPI (and IDE, they're different) device/vendor strings has now been added to the firmware. Firmware [https://github.com/ZuluIDE/ZuluIDE-firmware/releases/tag/v2024.07.02](v2024.07.02) incorporates these changes. See the example zuluide.ini. Support for pre-set drives will be added in a subsequent release.
