### ISSUE TITLE
Startup delay when ZuluIDE is a single drive

### ISSUE THREAD

**Issue by zouppen** [ZuluIDE/ZuluIDE-firmware#45]
During testing of bug #44 I found out that when ZuluIDE is a single drive, the startup time is slower compared to e.g. hard drive.

Petteri proposed this might be related to `IDE_CMD_IDENTIFY_PACKET_DEVICE` response, making the motherboard assume the presence of another drive, making it poll for a while after giving up.

This is a non-severe case in my opinion because the system eventually starts and ZuluIDE is correctly detected, adding 10-15 second delay to the startup on  ASUSTeK P5GZ-MX at least.

Might be a good idea to check this before new hardware version is produced to make sure this is just a firmware issue and if this issue is reproducible on other motherboards.

**Comment by aperezbios** [comment]
Closing as resolved, there have been numerous fixes in the year since this was filed, several of which would have likely been related to this.
