### ISSUE TITLE
Windows 98 SE installation does not detect ZuluIDE as a CD drive

### ISSUE THREAD

**Issue by nvllsvm** [ZuluIDE/ZuluIDE-firmware#98]
The Windows 98 SE (OEM) installation CD does not detect the ZuluIDE as a CD drive. The installation uses a universal driver which I've confirmed works with a Plextor PX-760A (released 2006) - amongst other drives. 

![out](https://github.com/user-attachments/assets/0c632a67-a19f-4b2b-8ffd-ba384d36b555)

### Info

**Disc Image:** [Windows 98 Second Edition (OEM Full)](https://winworldpc.com/download/417d71c2-ae18-c39a-11c3-a4e284a2c3a5)
**Disc Image (sha256):** 2adfb46df8a9c7bbd2f67bff07461cc2f9d9ec8e01f0e112cb044c9e3e62f607

In addition to the default config, I also tried the following:
```
[IDE]
device = CDROM
atapi_vendor = "PLEXTOR"
atapi_product = "DVDR   PX-760A"
atapi_version = "1.07"
```

### Log
**Note:** The driver attempts to find a drive starting at **137651ms**
[zululog.txt](https://github.com/user-attachments/files/16515727/zululog.txt)

### Notes:
Output of `sq_inq --vendor /dev/sr0` for the Plextor PX-760A
```
standard INQUIRY:
  PQual=0  PDT=5  RMB=1  LU_CONG=0  hot_pluggable=0  version=0x05  [SPC-3]
  [AERC=0]  [TrmTsk=0]  NormACA=1  HiSUP=1  Resp_data_format=2
  SCCS=0  ACC=0  TPGS=0  3PC=0  Protect=0  [BQue=0]
  EncServ=0  MultiP=0  [MChngr=0]  [ACKREQQ=0]  Addr16=0
  [RelAdr=0]  WBus16=0  Sync=0  [Linked=0]  [TranDis=0]  CmdQue=0
  [SPI: Clocking=0x0  QAS=0  IUS=0]
    length=96 (0x60)   Peripheral device type: cd/dvd
 Vendor identification: PLEXTOR 
 Product identification: DVDR   PX-760A  
 Product revision level: 1.07
 Vendor specific: 08/18/07  15:10     
```

Output of `sq_inq --vendor /dev/sr0` for the ZuluIDE (with modified atapi_ values)
```
standard INQUIRY:
  PQual=0  PDT=5  RMB=1  LU_CONG=0  hot_pluggable=0  version=0x05  [SPC-3]
  [AERC=0]  [TrmTsk=0]  NormACA=1  HiSUP=1  Resp_data_format=2
  SCCS=0  ACC=0  TPGS=0  3PC=0  Protect=0  [BQue=0]
  EncServ=0  MultiP=0  [MChngr=0]  [ACKREQQ=0]  Addr16=0
  [RelAdr=0]  WBus16=0  Sync=0  [Linked=0]  [TranDis=0]  CmdQue=0
    length=36 (0x24)   Peripheral device type: cd/dvd
 Vendor identification: PLEXTOR
 Product identification: DVDR   PX-760A
 Product revision level: 1.07
```

**Comment by aperezbios** [comment]
@nvllsvm we're able to reproduce this in-house as well, so we will get it dealt with shortly.

**Comment by morio** [comment]
@nvllsvm try this build. 
I was able to install your iso on a machine, but the machine isn't fully compatible with Win98 so I could only boot into Safe Mode.

**Comment by aperezbios** [comment]
@nvllsvm we've decided to cut a new release which incorporates the above change, so please test with https://github.com/ZuluIDE/ZuluIDE-firmware/releases/tag/v2024.08.14 instead.

**Comment by nvllsvm** [comment]
I haven't tested a full installation, but can confirm that the Win 98 setup CD detects the ZuluIDE and begins setup.
